spring:
  profiles: 
    active: dev 
  
  thymeleaf:
    check-template-location: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    servlet:
      content-type: text/html 

  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**



 

